wormhole-foundation/wormhole-explorer

fly/guardiansets/gst_data.go
fly/main.go

10 - Adds multiple guardian set support

---

Tiltfile
api/handlers/infraestructure/controller.go
api/handlers/infraestructure/model.go
api/handlers/infraestructure/repository.go
api/handlers/infraestructure/service.go
api/main.go
devnet/fly.yaml
fly/go.mod
fly/go.sum
fly/internal/sqs/sqs_consumer.go
fly/main.go
fly/migration/migration.go
fly/server/controller.go
fly/server/server.go
fly/storage/documents.go
fly/storage/repository.go

* Add index to collections.
* Create health/ready endpoint in fly.
* * Create health/ready endpoint in api.

Add index collections and health/ready kubernetes

---

api/handlers/guardian/guardian_set.go
fly/Makefile
fly/guardiansets/gst_data.go

- added xLabs guardian
- removed FTX

add new guardian set v3

---

fly/cmd/backfiller/README.md
fly/cmd/backfiller/main.go
fly/cmd/backfiller/txhash_strategy.go
fly/cmd/backfiller/vaa_strategy.go
fly/cmd/backfiller/workpool.go
fly/go.mod
fly/go.sum
fly/storage/repository.go

- generic backfiller for VAAs and txHashes

Fly backfiller

---

api/handlers/vaa/repository.go
api/handlers/vaa/service.go
api/routes/wormscan/vaa/controller.go

Add query parameter `parsedPayload` to the endpoint `GET /api/v1/vaas`.

[API] Add parsed payloads to `GET /api/v1/vaas`

---

api/Makefile
api/internal/build/build.go
api/routes/wormscan/infrastructure/controller.go
api/routes/wormscan/routes.go

- get branch and build date for deployed binary

add version endpoint

---

parser/internal/sqs/sqs_consumer.go
parser/pipeline/consumer.go
parser/queue/queue.go
parser/queue/vaa_memory.go
parser/queue/vaa_sqs.go

Co-authored-by: walker-16 <agpazos85@gmail.com>

Fix: parser memory leaks in sqs consumer

---

api/docs/docs.go
api/docs/swagger.json
api/docs/swagger.yaml
api/routes/wormscan/vaa/controller.go

Remove unused path parameters `GET /api/v1/vaas/{chain_id}/{emitter}/{seq}`

[API] Remove unused path parameters

---

api/handlers/governor/repository.go
api/handlers/observations/repository.go
api/handlers/vaa/repository.go
api/handlers/vaa/service.go
api/internal/pagination/pagination.go

Stacked on top of https://github.com/wormhole-foundation/wormhole-explorer/pull/147

[API] Remove redundant checks

---

api/handlers/governor/repository.go

Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/162
Changes:
* Fix `page` and `pageSize` parameters in `GET /api/v1/governor/notional/available/{chainId}`.
* Sort results by ascending guardian address to enforce deterministic output.
This PR is stacked on top of https://github.com/wormhole-foundation/wormhole-explorer/pull/167

[API] Fix pagination in `GET /api/v1/governor/notional/available/{chainId}`

---

fly/config/config.go
fly/go.mod
fly/go.sum
fly/guardiansets/guardianset.go
fly/main.go

Remove duplicated constants, use the definitions in the `common` package instead.

[FLY] Remove duplicated code

---

api/middleware/extract_parameters.go

This PR enables passing emitter addresses in Solana format when the `chainId` parameter is set to 1. If `chainId` is set to a different value, the API will expect a regular Wormhole address.
Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/189
- `GET /api/v1/global-tx/{chain_id}/{emitter}/{seq}`
- `GET /api/v1/observations/:chain/:emitter`
- `GET /api/v1/observations/:chain/:emitter/:sequence`
- `GET /api/v1/observations/:chain/:emitter/:sequence/:signer/:hash`
- `GET /api/v1/vaas/{chain_id}/{emitter}`
- `GET /api/v1/vaas/{chain_id}/{emitter}/{seq}`
These two calls should be equivalent:
- `GET /api/v1/vaas/1/ec7372995d5cc8732397fb0ad35c0121e0eaa90d26f828a534cab54391b3a4f5` (address in Wormhole format)
- `GET …

[API] Accept emitter addresses in Solana format

---

deploy/tx-tracker-backfiller/tx-tracker-backfiller-job.yaml
tx-tracker/chains/eth.go
tx-tracker/cmd/backfiller/main.go
tx-tracker/consumer/repository.go

Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/219

Optimize tx-tracker backfiller

---

contract-watcher/cmd/main.go
contract-watcher/internal/solana/client.go
contract-watcher/watcher/solana_watcher.go

Fix status for solana

---

analytics/cmd/service/run.go

Often times, the analytics service fails to start due to connectivity issues with other services (specifically redis).
Previously, no log information was being emitted, which made it hard to troubleshoot the exact reason for the service failing to start.
This pull request adds log messages when the service starts to make those cases easier to debug.

Add log messages on analytics service startup

---

contract-watcher/go.mod
contract-watcher/go.sum
contract-watcher/internal/aptos/client.go
contract-watcher/watcher/aptos_watcher.go
contract-watcher/watcher/evm_standard_watcher.go
contract-watcher/watcher/evm_watcher.go
contract-watcher/watcher/solana_watcher.go
contract-watcher/watcher/terra_watcher.go

Fix status for aptos blockchain
Fix pagination for backfilling

Fix status for aptos blockchain

---

deploy/tx-tracker-backfiller/tx-tracker-backfiller-job.yaml
deploy/tx-tracker/tx-tracker-service.yaml
tx-tracker/chains/sui.go
tx-tracker/chains/tx.go
tx-tracker/config/structs.go

This pull request modifies the `tx-tracker` service to support the Sui blockchain.
In particular, this will make the Sui sender addresses available for the Wormhole Scan UI.

Add support for Sui in the `tx-tracker` service

---

api/go.mod
api/go.sum
api/main.go

- update redis storage to v0.2.0
- improve error handling

update storage version and improve error log

---

api/handlers/vaa/repository.go
api/handlers/vaa/service.go

Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/430
In `GET /api/v1/vaas?txHash={hash}`, searching for Aptos VAAs by transaction hash was not working correctly. This pull request fixes the issue.

Fix transaction hash search for Aptos

---

analytics/cmd/service/run.go
analytics/config/config.go
api/main.go
common/client/cache/notional/cache.go
deploy/analytics/analytics-service.yaml
deploy/api/api-service.yaml
deploy/common/configmap.yaml

- add cache prefix to analytics
- fix api constructor
- include env var on deploy

add prefix to chacheable and fix deploy

---

jobs/jobs/notional/notional.go

replace `-` with `:` for redis symbol prefix

fix separator

---

contract-watcher/watcher/aptos_watcher.go
contract-watcher/watcher/evm_standard_watcher.go
contract-watcher/watcher/evm_watcher.go
contract-watcher/watcher/solana_watcher.go
contract-watcher/watcher/terra_watcher.go

Co-authored-by: ftocal <fert1335@gmail.com>

Fix contract-watcher last block metrics

---

api/internal/tvl/tvlapi.go

Context: https://xlabs-org.slack.com/archives/C04483M8KL0/p1689780688370379?thread_ts=1689780056.595759&cid=C04483M8KL0

Update base URL for the external TVL API

---

api/handlers/transactions/repository.go
common/utils/hex.go
common/utils/hexutil.go
contract-watcher/internal/evm/client.go
contract-watcher/watcher/evm.go

Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/587
The endpoint `GET /api/v1/transactions?address={addr}` was incorrectly handling EVM addresses containing uppercase characters. This pull request fixes the issue.

Transaction search by address: fix case sensitivity

---

event-watcher/package.json
event-watcher/src/builder/server.ts
event-watcher/src/databases/MongoDB.ts
event-watcher/src/databases/utils.ts
event-watcher/src/index.ts
event-watcher/src/infrastructure/infrastructure.controller.ts

- add support for mongo database
- add infrastructure service

add mongo db mock and infra

---

tx-tracker/consumer/consumer.go
tx-tracker/consumer/processor.go
tx-tracker/consumer/repository.go
tx-tracker/queue/queue.go
tx-tracker/queue/vaa_sqs.go

Add logic to fix vaa txhash in tx-tracker component.

---

event-watcher/src/consts.ts
event-watcher/src/databases/utils.ts
event-watcher/src/services/SNS/utils.ts
event-watcher/src/watchers/NearWatcher.ts
event-watcher/src/watchers/TerraExplorerWatcher.ts
event-watcher/src/watchers/utils.ts

- Add `Near` support
- Add `Terra` support

feat: add near and terra support

---

event-watcher/package-lock.json
event-watcher/package.json
event-watcher/src/consts.ts
event-watcher/src/watchers/BaseWatcher.ts
event-watcher/src/watchers/WormchainWatcher.ts
event-watcher/src/watchers/utils.ts

- Add `Wormchain` support:
-  `LogMessagePublished` event workflow

feat(743): add Wormchain support

---

tx-tracker/chains/api_wormchain.go

Co-authored-by: ftocal <fert1335@gmail.com>

normalize osmosis txhash

---

blockchain-watcher/src/infrastructure/repositories/EvmJsonRPCBlockRepository.ts
blockchain-watcher/test/infrastructure/repositories/EvmJsonRPCBlockRepository.integration.test.ts

https://github.com/wormhole-foundation/wormhole-explorer/issues/817
- Set hexadecimal block into getBlocks and getBlock method

[Blockchain Watcher] Feature 817/add hexagonal prefix

---

blockchain-watcher/config/default.json
blockchain-watcher/config/prod-mainnet.json
blockchain-watcher/config/staging-mainnet.json
blockchain-watcher/src/infrastructure/RepositoriesBuilder.ts
blockchain-watcher/test/infrastructure/repositories/RepositoriesBuilder.test.ts
blockchain-watcher/test/mocks/configMock.ts
deploy/blockchain-watcher/workers/ethereum.yaml

- Add fantom supporter chain
Build fantom repository
Mainnet test
`
[
{
"id": "poll-log-message-published-fantom",
"chain": "fantom",
"source": {
"config": {
"interval": 100,
"addresses": ["0x126783A6Cb203a3E35344528B26ca3a0489a1485"],
"chain": "fantom",
"topics": []
}
},
"handlers": [
{
"config": {
"filter": {
"addresses": ["0x126783A6Cb203a3E35344528B26ca3a0489a1485"],
"topics": …

[Blockchain Watcher] Add fantom chain

---

blockchain-watcher/config/default.json
blockchain-watcher/config/prod-mainnet.json
blockchain-watcher/config/staging-mainnet.json
blockchain-watcher/src/infrastructure/RepositoriesBuilder.ts
blockchain-watcher/test/infrastructure/repositories/RepositoriesBuilder.test.ts
blockchain-watcher/test/mocks/configMock.ts
deploy/blockchain-watcher/workers/ethereum.yaml

- Add acala supporter chain
Build acala repository
Mainnet test
`
{
"id": "poll-log-message-published-acala",
"chain": "acala",
"source": {
"config": {
"interval": 100,
"addresses": [
"0xa321448d90d4e5b0A732867c18eA198e75CAC48E"
],
"chain": "acala",
"topics": []
}
},
"handlers": [
{
"config": {
"filter": {
"addresses": [
"0xa321448d90d4e5b0A732867c18eA198e75CAC48E"
],
"topics": [ …

[Blockchain Watcher] Feature 798/enable evm acala chain

---

blockchain-watcher/config/custom-environment-variables.json
blockchain-watcher/config/default.json
blockchain-watcher/config/mainnet.json
blockchain-watcher/src/infrastructure/repositories/RepositoriesBuilder.ts
blockchain-watcher/test/infrastructure/repositories/RepositoriesBuilder.test.ts
blockchain-watcher/test/mocks/configMock.ts
deploy/blockchain-watcher/workers/ethereum-1.yaml

- Add base supporter chain
Build base repository
Mainnet test
`
[
{
"id": "poll-log-message-published-base",
"chain": "base",
"source": {
"config": {
"interval": 100,
"addresses": ["0x23908A62110e21C04F3A4e011d24F901F911744A"],
"chain": "base"
}
},
"handlers": [
{
"config": {
"filter": {
"addresses": ["0x23908A62110e21C04F3A4e011d24F901F911744A"],
"topics": ["0x6eb224fb001ed210e379b335e35efe88672a8ce935d981a6896b27ffdf52a3b2"]
}
}
}
] …

[Blockchain Watcher](EVM) Add base chain

---

blockchain-watcher/config/custom-environment-variables.json
blockchain-watcher/config/default.json
blockchain-watcher/config/mainnet.json
blockchain-watcher/src/infrastructure/repositories/RepositoriesBuilder.ts
blockchain-watcher/test/infrastructure/repositories/RepositoriesBuilder.test.ts
blockchain-watcher/test/mocks/configMock.ts
deploy/blockchain-watcher/workers/ethereum-1.yaml

- Add Klaytn supporter chain
Build Klaytn repository
Mainnet test
-
`
[
{
"id": "poll-log-message-published-Klaytn",
"chain": "Klaytn",
"source": {
"config": {
"interval": 5000,
"addresses": ["0x0C21603c4f3a6387e241c0091A7EA39E43E90bb7"],
"chain": "Klaytn"
}
},
"handlers": [
{
"config": {
"filter": {
"addresses": ["0x0C21603c4f3a6387e241c0091A7EA39E43E90bb7"],
"topics": ["0x6eb224fb001ed210e379b335e35efe88672a8ce935d981a6896b27ffdf52a3b …

[Blockchain Watcher](EVM) Add Klaytn chain

---

blockchain-watcher/config/custom-environment-variables.json
blockchain-watcher/config/default.json
blockchain-watcher/config/mainnet.json
blockchain-watcher/src/infrastructure/repositories/RepositoriesBuilder.ts
blockchain-watcher/test/infrastructure/repositories/RepositoriesBuilder.test.ts
blockchain-watcher/test/mocks/configMock.ts
deploy/blockchain-watcher/workers/ethereum-1.yaml

- Add oasis supporter chain
Build oasis repository
Mainnet test
-
`
[
{
"id": "poll-log-message-published-oasis",
"chain": "oasis",
"source": {
"config": {
"interval": 5000,
"addresses": ["0xfE8cD454b4A1CA468B57D79c0cc77Ef5B6f64585"],
"chain": "oasis"
}
},
"handlers": [
{
"config": {
"filter": {
"addresses": ["0xfE8cD454b4A1CA468B57D79c0cc77Ef5B6f64585"],
"topics": ["0x6eb224fb001ed210e379b335e35efe88672a8ce935d981a6896b27ffdf52a3b2"] …

[Blockchain Watcher](EVM) Add oasis chain

---

api/routes/wormscan/relays/controller.go

Co-authored-by: ftocal fert1335@gmail.com

Add fields int the relay endpoint

---

contract-watcher/cmd/service/run.go
contract-watcher/http/infrastructure/server.go
contract-watcher/http/redeem/controller.go
contract-watcher/watcher/aptos_watcher.go
contract-watcher/watcher/contract_tracker.go
contract-watcher/watcher/evm_standard_watcher.go
contract-watcher/watcher/evm_watcher.go
contract-watcher/watcher/solana_watcher.go
contract-watcher/watcher/terra_watcher.go

Handling transactions with more than one instruction in solana watcher

---

analytics/queue/event_sqs.go
common/client/sqs/consumer.go
parser/internal/sqs/sqs_consumer.go
parser/queue/event_sqs.go
tx-tracker/consumer/consumer.go
tx-tracker/queue/converter.go
tx-tracker/queue/event_sqs.go

Delete unhandled messages from sqs

---

blockchain-watcher/config/mainnet.json

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1018
- Replace public url in mainnet
- Not apply

[Blockchain Watcher] (EVM) Replace public url in mainnet

---

blockchain-watcher/src/domain/actions/evm/GetEvmTransactions.ts
blockchain-watcher/test/domain/actions/evm/GetEvmTransactions.test.ts

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1020
- Mapped all blocks inside transactions for

[Blockchain Watcher] (EVM)[FIX] Mapped all blocks inside transactions for 

---

blockchain-watcher/src/domain/actions/evm/GetEvmTransactions.ts
blockchain-watcher/src/infrastructure/mappers/evm/evmRedeemedTransactionFoundMapper.ts
blockchain-watcher/src/infrastructure/mappers/evm/methodNameByAddressMapper.ts
blockchain-watcher/src/infrastructure/repositories/evm/EvmJsonRPCBlockRepository.ts
blockchain-watcher/test/infrastructure/mappers/evm/evmRedeemedTransactionFoundMapper.test.ts
blockchain-watcher/test/infrastructure/mappers/evm/methodNameByAddressMapper.test.ts
blockchain-watcher/test/infrastructure/repositories/EvmJsonRPCBlockRepository.integration.test.ts

- 
- Change evm redeemed transaction mapper
- Evm transfer redeem example
'{"name":"transfer-redeemed","address":"0x4cb69fae7e7af841e44e1a1c30af640739378bb2","chainId":5,"txHash":"0x8e77af1115123e09916b3ee77edeed3149840591b2f56f2940c13ee9af1a34c1","blockHeight":"52659804","blockTime":1706017305,"attributes":{"from":"0x0926afb630cfbfdfeb1c7cc26e435c2b473b86b7","to":"0x4cb69fae7e7af841e44e1a1c30af640739378bb2","status":"completed","blockNumber":"0x323865c","input":"0x0a55d7350000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000048701 …

[Blockchain Watcher] (EVM) Change evm redeemed transaction mapper

---

blockchain-watcher/config/mainnet.json
blockchain-watcher/src/infrastructure/repositories/evm/EvmJsonRPCBlockRepository.ts

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1036
- Fix quantity logs process per block
- Not apply

[Blockchain Watcher] (FIX) Fix quantity logs process per block

---

analytics/cmd/token/token.go
analytics/metric/metric.go
analytics/scripts/top_100_corridors_3h.flux
api/docs/docs.go
api/docs/swagger.json
api/docs/swagger.yaml
api/handlers/stats/queries.go
api/handlers/stats/repository.go
api/handlers/stats/service.go
api/handlers/stats/types.go
api/middleware/extract_parameters.go
api/routes/wormscan/routes.go
api/routes/wormscan/stats/controller.go
api/routes/wormscan/stats/models.go

Improve handling token in volume metrics

Add top-100-corridors endpoint

---

fly/migration/migration.go

Co-authored-by: ftocal fert1335@gmail.com

Fix globalTransactions index in fly

---

deploy/blockchain-watcher/workers/solana-source-events.yaml
deploy/blockchain-watcher/workers/solana-target-events.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1084
- Divided solana pods in source and target events
- Not aply

[Blockchain Watcher] (FIX)  Divided solana pods

---

api/routes/wormscan/address/controller.go
api/routes/wormscan/governor/controller.go
api/routes/wormscan/observations/controller.go
api/routes/wormscan/transactions/controller.go
api/routes/wormscan/vaa/controller.go

Co-authored-by: ftocal fert1335@gmail.com

Add pageSize max value to 1000 in api

---

blockchain-watcher/config/mainnet.json
blockchain-watcher/package.json
blockchain-watcher/src/infrastructure/rpc/http/InstrumentedHttpProvider.ts

- 
- Add content type header in post request
- Not aply

[Blockchain Watcher] (FIX) Add content type header

---

blockchain-watcher/src/domain/actions/sui/PollSuiTransactions.ts
blockchain-watcher/src/infrastructure/mappers/evm/evmRedeemedTransactionFoundMapper.ts

-
- Improve evm log and sui cursor
- Sui without max cursos value

[Blockchain Watcher] (FIX) Improve evm logs

---

blockchain-watcher/src/infrastructure/repositories/evm/EvmJsonRPCBlockRepository.ts

-
- Add transactions in evm request
-

[Blockchain Watcher] (FIX) Add transactions in evm request

---

blockchain-watcher/config/mainnet.json
blockchain-watcher/src/infrastructure/mappers/sui/suiLogMessagePublishedMapper.ts
blockchain-watcher/src/infrastructure/mappers/sui/suiRedeemedTransactionFoundMapper.ts
blockchain-watcher/src/infrastructure/repositories/StaticJobRepository.ts
blockchain-watcher/test/infrastructure/mappers/sui/suiLogMessagePublishedMapper.test.ts
blockchain-watcher/test/infrastructure/mappers/sui/suiRedeemedTransactionFoundMapper.test.ts
deploy/blockchain-watcher/workers/source-events.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/894
- Mapped sui source event
- Source event:

[Blockchain Watcher] (SUI) Mapped sui source event

---

blockchain-watcher/config/default.json
blockchain-watcher/src/infrastructure/repositories/RepositoriesBuilder.ts
blockchain-watcher/test/infrastructure/repositories/RepositoriesBuilder.test.ts
blockchain-watcher/test/mocks/configMock.ts
deploy/blockchain-watcher/workers/source-events-1.yaml
deploy/blockchain-watcher/workers/source-events.yaml
deploy/blockchain-watcher/workers/target-events.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1138
- Add holesky network for eth in testnet
- Source event:
- Target: We dont have events

[Blockchain Watcher] (ETH HOLSKY) Add eth holesky for testnet

---

blockchain-watcher/config/mainnet.json
blockchain-watcher/src/domain/actions/evm/HandleEvmTransactions.ts
blockchain-watcher/src/domain/actions/solana/HandleSolanaTransactions.ts
blockchain-watcher/src/domain/actions/sui/HandleSuiTransactions.ts
blockchain-watcher/src/domain/entities/events.ts
blockchain-watcher/src/infrastructure/mappers/contractsMapper.ts
blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
blockchain-watcher/src/infrastructure/mappers/evm/evmRedeemedTransactionFoundMapper.ts
blockchain-watcher/src/infrastructure/mappers/solana/solanaTransferRedeemedMapper.ts
blockchain-watcher/src/infrastructure/mappers/sui/suiRedeemedTransactionFoundMapper.ts
blockchain-watcher/test/domain/actions/solana/HandleSolanaTransactions.test.ts
blockchain-watcher/test/domain/actions/sui/HandleSuiTransactions.test.ts
blockchain-watcher/test/infrastructure/mappers/sui/suiRedeemedTransactionFoundMapper.test.ts
deploy/blockchain-watcher/workers/backfiller.yaml

- 
-  Mapped sui protocol for manual or automatic event in redeemed events
- Test new metrics with mapped protocols

[Blockchain Watcher] (FIX) Mapped sui protocol

---

blockchain-watcher/src/domain/actions/sui/HandleSuiTransactions.ts
deploy/blockchain-watcher/workers/source-events.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1171
- Fix logs events for SUI
- Move labels to json config

[Blockchain Watcher] (FIX) Move labels to json config

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1154
-  Mapped MethodRedeemAndUnwrap method
- Not recognized mayan tx because does not map the method id = 0xc0e6d169
- Link to tx: https://wormholescan.io/#/tx/5YwJix6EEFjwM7cFhVQbmbxw6NV1U3kasTmhTnBG1VmYA8FrSBn4vWUYhBBxTwCJmEdbEzeQD5CzBuFuvU39kLt

[Blockchain Watcher] (MAYAN) Mapped MethodRedeemAndUnwrap method

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/target-events-1.yaml

- Mapped mayan with payload contract: 0xe1c66210fb97c76cdaee38950f5e9c181e9da628
- Tx in mainnet:
https://wormholescan.io/#/tx/qttDxqHsdQEwMVuXczkdEZrAs37P1PBgkvkN15cXkxumV2SAtLnDXyUwDkNKQPG6hXQFqCR1NocLvHUmX6JBRZk
- Test:

[Blockchain Watcher] (FIX - MAYAN) Add mayan with payload address

---

analytics/cmd/token/token.go
analytics/consumer/consumer.go
analytics/internal/metrics/metrics.go
analytics/internal/metrics/noop.go
analytics/internal/metrics/prometheus.go
analytics/queue/converter.go
analytics/queue/event_sqs.go
analytics/queue/types.go
common/client/parser/parser.go
common/client/parser/parser_test.go

Add retry in analytics metrics

Handle unproccessable response from vaa-payload-parser

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/target-events-1.yaml

- Address
WH: 0xBF5f3f65102aE745A48BD521d10BaB5BF02A9eF4
MCTP: 0x8B782997B28e00eD8379Ae8b27D4E4ddFC43967e

[Blockchain Watcher] (FIX - MAYAN) Mapped new address

---

common/domain/chainid.go
tx-tracker/consumer/target_processor.go

Co-authored-by: ftocal <fert1335@gmail.com>

Normalize txHash destination in tx-tracker component

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/target-events-1.yaml
deploy/blockchain-watcher/workers/target-events-2.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1276
- Integrate support NTT for fantom and ETH
- Mainnet contact: 
- Fantom: 0x8b47f02E7E20174C76Af910adc0Ad8A4B0342f4c 
- ETH: 0x55f7820357fa17a1ecb48e959d5e637bff956d6f
- Mainnet topic: 0x504e6efe18ab9eed10dc6501a417f5b12a2f7f2b1593aed9b89f9bce3cf29a91
FANTOM
ETHEREUM

[Blockchain Watcher] (NTT - FANTOM and ETH) Integrate support NTT for fantom

---

blockchain-watcher/config/custom-environment-variables.json
blockchain-watcher/src/domain/actions/aptos/GetAptosTransactions.ts
blockchain-watcher/src/domain/actions/aptos/GetAptosTransactionsByEvents.ts
blockchain-watcher/src/domain/actions/aptos/PollAptos.ts
blockchain-watcher/src/domain/repositories.ts
blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
blockchain-watcher/src/infrastructure/mappers/sui/suiRedeemedTransactionFoundMapper.ts
blockchain-watcher/src/infrastructure/repositories/aptos/AptosJsonRPCBlockRepository.ts
blockchain-watcher/src/infrastructure/repositories/aptos/RateLimitedAptosJsonRPCBlockRepository.ts
blockchain-watcher/test/domain/actions/aptos/GetAptosTransactions.test.ts
blockchain-watcher/test/domain/actions/aptos/GetAptosTransactionsByEvents.test.ts
deploy/blockchain-watcher/workers/solana-target-events-1.yaml
deploy/blockchain-watcher/workers/source-events-1.yaml
deploy/blockchain-watcher/workers/target-events-1.yaml
deploy/blockchain-watcher/workers/target-events-2.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1146
-  Mapped contracts
solana
MAINNET: WnFt12ZrnzZrFZkt2xsNsaNWoQribnuQ5B5FrDbwDhD
TESTNET: 2rHhojZ7hpu1zA91nvZmT8TqWWvMcKmmNBCr2mKTtMq4
aptos
MAINNET: 0x1bdffae984043833ed7fe223f7af7a3f8902d04129b14f801823e64827da7130
TESTNET: 0x1bdffae984043833ed7fe223f7af7a3f8902d04129b14f801823e64827da7130
arbitrum
MAINNET: 0x3dD14D553cFD986EAC8e3bddF629d82073e188c8
TESTNET SEPOLIA: 0x23908A62110e21C04F3A4e011d24F901F911744A
avalanche
MAINNET: 0xf7B6737Ca9c4e08aE573F75A97B73D7a813f5De5
TESTNET: 0xD601BAf2EEE3C028344471684F6b27E789D9075D
base
MAINNET: 0xDA3adC6621B2677BEf9aD26598e6939CF0D92f88
TESTNET SEPOLIA: 0x268557122Ffd64c85750d630b716471118F323c8
celo
MAINNET: 0xA6A377d75ca5c9052c9a77ED1e865Cc25Bd97bf3
TESTNET: …

[Blockchain Watcher] (NFT) Mapped contracts

---

blockchain-watcher/config/custom-environment-variables.json
blockchain-watcher/config/default.json
blockchain-watcher/config/mainnet.json
blockchain-watcher/src/infrastructure/repositories/RepositoriesBuilder.ts
blockchain-watcher/test/infrastructure/repositories/RepositoriesBuilder.test.ts
blockchain-watcher/test/mocks/configMock.ts
deploy/blockchain-watcher/workers/source-events-1.yaml
deploy/blockchain-watcher/workers/source-events-2.yaml
deploy/blockchain-watcher/workers/target-events-2.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1279
-  Mapped scroll source and target events
- TESTNET SOURCE EVENT
tx: https://sepolia.scrollscan.com/tx/0x9f59b290c1e4dc47a28142ce3287c89af9bcc0b1d95ddd153cdec857b936ee72

[Blockchain Watcher] (SCROLL) Mapped scroll source and target events

---

deploy/blockchain-watcher/workers/target-events-1.yaml

- 
-  Remove deprecated arbitrum goerli in testnet

[Blockchain Watcher] (ARBITRUM) Remove arbitrum goerli in testnet

---

deploy/blockchain-watcher/workers/target-events-1.yaml
deploy/blockchain-watcher/workers/target-events-2.yaml

- 
-  Mapped standard relayer for fantom, celo and moonbeam
Fantom

[Blockchain Watcher] (STANDARD RELAYER) Map new chains

---

blockchain-watcher/src/domain/actions/wormchain/PollWormchain.ts
blockchain-watcher/src/domain/entities/evm.ts
blockchain-watcher/src/infrastructure/mappers/evm/evmLogMessagePublishedMapper.ts
blockchain-watcher/src/infrastructure/repositories/evm/EvmJsonRPCBlockRepository.ts
blockchain-watcher/test/domain/actions/evm/GetEvmTransactions.test.ts
blockchain-watcher/test/domain/actions/evm/HandleEvmLogs.test.ts
blockchain-watcher/test/domain/actions/evm/PollEvm.test.ts
blockchain-watcher/test/infrastructure/mappers/evm/evmLogMessagePublishedMapper.test.ts

- Improve MAX value for wormchain
- Map chain for evm source events and add log for these events in the mapper

[Blockchain Watcher] (FIX)  Add logs for evm source events

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
blockchain-watcher/src/infrastructure/mappers/solana/solanaTransferRedeemedMapper.ts
deploy/blockchain-watcher/workers/solana-target-events-1.yaml

- Mapped solana redeem with config instructions
Run and mapped nft solana redeem
https://dev.wormholescan.io/#/tx/2/0000000000000000000000006ffd7ede62328b3af38fcd61461bbfc52f5651fe/1272

[Blockchain Watcher] (FIX - SOLANA) Map config for solana

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/solana-target-events-1.yaml

Example VAA: https://wormholescan.io/#/tx/24/0000000000000000000000009bd8b7b527ca4e6738cbdabdf51c22466756073d/9
Redeem tx: [3dH16RHhc1ziAWb4MUEtmPCqf793cBV8zHMJcewvuSB6kyqtuGjK9fUr6LPLWBajTkwYd1VwjUUTb3tbHz7MZZKt](https://solscan.io/tx/3dH16RHhc1ziAWb4MUEtmPCqf793cBV8zHMJcewvuSB6kyqtuGjK9fUr6LPLWBajTkwYd1VwjUUTb3tbHz7MZZKt)

Add W token NTT redeem tracking for solana

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/solana-target-events-1.yaml
deploy/blockchain-watcher/workers/source-events-1.yaml
deploy/blockchain-watcher/workers/target-events-1.yaml
deploy/blockchain-watcher/workers/target-events-2.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1339
-  Remove the CCTP redeem event.
We have decided to discontinue the CCTP redeem event, focusing solely on the wormhole CCTP redemption. 
*However, on the future we can use the CCTP native event to map the manual redeems
Doc: https://developers.circle.com/stablecoins/docs/evm-smart-contracts
-

[Blockchain Watcher] (CCTP) Remove CCTP contracts

---

blockchain-watcher/config/mainnet.json
blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/source-events-2.yaml
deploy/blockchain-watcher/workers/target-events-2.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1279
Map scroll mainnet contracts
Mainnet:
- core: "0xbebdb6C8ddC678FfA9f8748f85C815C556Dd8ac6",
- token_bridge: "0x24850c6f61C438823F01B7A3BF2B89B72174Fa9d",
SOURCE job
REDEEM job

[Blockchain Watcher] (SCROLL) Map scroll mainnet contracts

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/target-events-1.yaml
deploy/blockchain-watcher/workers/target-events-2.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1318
- Integrate connect redeem
`MAINNET contracts`
Ethereum 0xcafd2f0a35a4459fa40c0517e17e6fa2939441ca
polygon 0xcafd2f0a35a4459fa40c0517e17e6fa2939441ca
bsc 0xcafd2f0a35a4459fa40c0517e17e6fa2939441ca
fantom  0xcafd2f0a35a4459fa40c0517e17e6fa2939441ca
avalanche 0xcafd2f0a35a4459fa40c0517e17e6fa2939441ca
moonbean 0xcafd2f0a35a4459fa40c0517e17e6fa2939441ca
celo 0xcafd2f0a35a4459fa40c0517e17e6fa2939441ca
`TESTNET contracts`
ethereum 0x9563a59C15842a6f322B10f69d1dD88b41f2E97B
polygon 0x9563a59C15842a6f322B10f69d1dD88b41f2E97B
bsc 0x9563a59C15842a6f322B10f69d1dD88b41f2E97B
fantom 0x9563a59C15842a6f322B10f69d1dD88b41f2E97B
avalanche 0x9563a59C15842a6f322B10f69d1dD88b41f2E97B
moonbean 0x9563a59C15842a6f322B10f69d1dD88b41f2E97B …

[Blockchain Watcher] (CONNECT) Integrate connect redeem

---

blockchain-watcher/config/mainnet.json

Map rpcs for wormchain mainnet

[Blockchain Watcher] (WORMCHAIN - FIX) Map rpcs for wormchain mainnet

---

deploy/blockchain-watcher/workers/target-events-2.yaml

- Add topics for scroll chain
- Reduce time in jobs executions for celo

[Blockchain Watcher] (SCROLL - CELO) Add topics for scroll chain

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/target-events-1.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1376
Map contracts for ETH and arbitrum
- mainnet arbitrum: 0x89e928e6d95ba6d7419b2b9e384fc526b1649339
- mainnet eth: 0x45E581d6841F0a99Fc34F70871ef56b353813ddb, 0x0e9c1B26Ee0D3021e4543c2Ed65a9661AC390390
ARBITRUM
ETH

[Blockchain Watcher] (NTT) Map contracts for ETH and arbitrum

---

blockchain-watcher/config/mainnet.json
blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/source-events-1.yaml
deploy/blockchain-watcher/workers/source-events-2.yaml
deploy/blockchain-watcher/workers/source-events-3.yaml
deploy/blockchain-watcher/workers/target-events-1.yaml
deploy/blockchain-watcher/workers/target-events-2.yaml
deploy/blockchain-watcher/workers/target-events-3.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1381
Map portal and Omniswap
- PORTAL ARBITRUM
- PORTAL OPTIMISM
- PORTAL BASE
- PORTAL BSC
We dont have any redeem redeemed 
- PORTAL AVALANCHE
- OMNISWAP ETH
- OMNISWAP POLYGON
- OMNISWAP BSC
We dont have any redeem redeemed

[Blockchain Watcher] (PORTAL - OMNISWAP) Map portal and Omniswap redeems

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/target-events-1.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1417
Map CCTP transactions
- New contract: 0x5367066c34d487458811eFB506a7a2AFDADb8e8b
AVALANCHE

[Blockchain Watcher] (CCTP) Map avalanche contract

---

blockchain-watcher/config/custom-environment-variables.json
blockchain-watcher/config/default.json
blockchain-watcher/config/mainnet.json
blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
blockchain-watcher/src/infrastructure/repositories/RepositoriesBuilder.ts
blockchain-watcher/test/infrastructure/repositories/RepositoriesBuilder.test.ts
blockchain-watcher/test/mocks/configMock.ts
deploy/blockchain-watcher/workers/source-events-1.yaml
deploy/blockchain-watcher/workers/source-events-3.yaml
deploy/blockchain-watcher/workers/target-events-3.yaml

- https://github.com/wormhole-foundation/wormhole-explorer/issues/1406
Map xlayer redeems
Mainnet:
- core: "0x194B123c5E96B9b2E49763619985790Dc241CAC0",
- token_bridge: "0x5537857664B0f9eFe38C9f320F75fEf23234D904",
Testnet:
- core: "0x194B123c5E96B9b2E49763619985790Dc241CAC0",
- token_bridge: "0x5537857664B0f9eFe38C9f320F75fEf23234D904",
SOURCE EVENTS:
TARGET EVENTS

[Blockchain Watcher] (XLAYER) Map xlayer redeems

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/target-events-2.yaml
deploy/blockchain-watcher/workers/target-events-3.yaml

[Blockchain Watcher] (STANDARD RELAYER(SCROLL - BLAST)) Map SR for scroll and blast

---

blockchain-watcher/src/domain/actions/RunPollingJob.ts
blockchain-watcher/src/domain/repositories.ts

- New metrics for job executions time when process an events
Example of metric:

[Blockchain Watcher] (METRICS) Create metrics for job executions

---

blockchain-watcher/config/mainnet.json

Map chain id in mainnet config

[Blockchain Watcher] (CONFIG )Map chain id in mainnet config

---

api/docs/docs.go
api/docs/swagger.json
api/docs/swagger.yaml
api/handlers/observations/model.go
api/handlers/observations/repository.go
api/handlers/observations/service.go
api/routes/wormscan/observations/controller.go
common/repository/names.go
deploy/jobs/migrate-native-tx-hash.yml
fly/go.mod
fly/migration/migration.go
fly/storage/documents.go
fly/storage/repository.go
jobs/cmd/main.go
jobs/config/config.go
jobs/jobs/jobs.go
jobs/jobs/migration/migration_native_tx_hash.go

Add txHash query parameter in observations endpoint
Add job to add nativeTxHash in observations collection except for solana, aptos and wormchain 
Add encoded txHash in obvervations collection

Find by txHash in observations endpoint

---

blockchain-watcher/src/domain/entities/wormchain.ts
blockchain-watcher/src/infrastructure/mappers/wormchain/wormchainLogMessagePublishedMapper.ts
blockchain-watcher/src/infrastructure/repositories/wormchain/WormchainJsonRPCBlockRepository.ts
blockchain-watcher/test/domain/actions/wormchain/HandleWormchainLogs.test.ts
blockchain-watcher/test/infrastructure/mappers/wormchain/wormchainLogMessagePublishedMapper.test.ts
blockchain-watcher/test/infrastructure/repositories/WormchainJsonRPCBlockRepository.test.ts
deploy/blockchain-watcher/workers/source-events-2.yaml
deploy/blockchain-watcher/workers/target-events-1.yaml

- [#896](https://github.com/wormhole-foundation/wormhole-explorer/issues/896)
Map sei source events

[Blockchain Watcher] (SEI) Map sei mainnet events

---

blockchain-watcher/config/custom-environment-variables.json
blockchain-watcher/config/default.json
blockchain-watcher/src/domain/actions/RunPollingJob.ts
blockchain-watcher/src/infrastructure/mappers/evm/evmRedeemedTransactionFoundMapper.ts

- Handle no healthy providers error
- Add custom variables for cosmos
- Improve vaa parser for EVM
- Map sei testnet rpcs

[Blockchain Watcher] (FIX) Improve vaa parser and no healthy process

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/solana-target-events-1.yaml

-[1415](https://github.com/wormhole-foundation/wormhole-explorer/issues/1415)
Map NTT contract for solana
- Transceiver: 6afkDMjQCod662yV22tBQGArRnwhCCWHKXTpnZPqxd8
We dont have transactions yet: https://explorer.solana.com/address/6afkDMjQCod662yV22tBQGArRnwhCCWHKXTpnZPqxd8?cluster=testnet

[Blockchain Watcher] (NTT - SOLANA) Map contract for NTT protocol

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/target-events-2.yaml

- [#1322](https://github.com/wormhole-foundation/wormhole-explorer/issues/1322)
Map karura redeem events
TEST GET REDEEM

[Blockchain Watcher] (KARURA) Map karura redeem events

---

common/domain/manual_mainnet_tokens.go

Add missing address for `W` and add new tokens `CHEESE` and `AGA`

Add NTT tokens to manual list

---

blockchain-watcher/config/mainnet.json
blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/target-events-3.yaml

- [#1320](https://github.com/wormhole-foundation/wormhole-explorer/issues/1320)
Map klaytn redeem events
REDEEM EVENTS

[Blockchain Watcher] (KLAYTN) Map klaytn redeem events

---

analytics/cmd/token/token.go
analytics/metric/metric.go

- Ticket: #1499 
- Add `from_address` and `to_address` to `vaa_volume_v3`

[#1499] Add from_address and to_address to vaa_volume_v3

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/target-events-3.yaml

- [#1320](https://github.com/wormhole-foundation/wormhole-explorer/issues/1321)
Map acala redeem events
REDEEM EVENTS

[Blockchain Watcher] (ACALA) Map acala redeem job

---

analytics/cmd/token/token.go

- Add `fromAddress` and `toAddress` to `TransferredToken.Clone`

 Add fromAddress and toAddress to TransferredToken.Clone

---

blockchain-watcher/src/infrastructure/mappers/algorand/algorandRedeemedTransactionFoundMapper.ts

- Validate method and payload in algorand redeem event

[Blockchain Watcher] (FIX - ALGORAND) Validate method and payload in algorand redeem event

---

blockchain-watcher/src/domain/actions/evm/GetEvmTransactions.ts
blockchain-watcher/src/domain/actions/solana/PollSolanaTransactions.ts
blockchain-watcher/src/domain/entities/events.ts
blockchain-watcher/src/domain/entities/evm.ts
blockchain-watcher/src/domain/entities/solana.ts
blockchain-watcher/src/infrastructure/mappers/evm/evmRedeemedTransactionFoundMapper.ts
blockchain-watcher/src/infrastructure/mappers/solana/solanaTransferRedeemedMapper.ts
blockchain-watcher/src/infrastructure/repositories/evm/EvmJsonRPCBlockRepository.ts
blockchain-watcher/test/domain/actions/evm/GetEvmTransactions.test.ts
blockchain-watcher/test/domain/actions/evm/PollEvm.test.ts
blockchain-watcher/test/infrastructure/mappers/evm/evmRedeemedTransactionFoundMapper.test.ts

- [#1517](https://github.com/wormhole-foundation/wormhole-explorer/issues/1517)
Map fee value for evm and solana
EVM
- tx: https://wormholescan.io/#/tx/1/EC7372995D5CC8732397FB0AD35C0121E0EAA90D26F828A534CAB54391B3A4F5/899534
SOLANA
- tx: https://wormholescan.io/#/tx/23/0000000000000000000000000b2402144bb366a632d14b83f244d2e0e21bd39c/266117

[Blockchain Watcher] (EVM and SOLANA) Map fee value for evm and solana

---

blockchain-watcher/src/domain/actions/evm/PollEvm.ts
blockchain-watcher/test/domain/actions/evm/PollEvm.test.ts

- Fix evm process blocks
Error

[Blockchain Watcher] (EVM) Fix evm process blocks

---

blockchain-watcher/src/domain/actions/evm/PollEvm.ts
blockchain-watcher/test/domain/actions/evm/PollEvm.test.ts

- Fix evm process blocks
Error

[Blockchain Watcher] (EVM) Fix improve evm process blocks

---

blockchain-watcher/src/infrastructure/repositories/wormchain/WormchainJsonRPCBlockRepository.ts
blockchain-watcher/test/infrastructure/repositories/WormchainJsonRPCBlockRepository.test.ts

- Improve blocktime value transform

[Blockchain Watcher] (WORMCHAIN - FIX) Improve blocktime value

---

deploy/blockchain-watcher/workers/solana-target-events-1.yaml

- Deployments NTT:
Yaku: nTtPcmsVY4f86cSREmnio5tUyiK58HBqBeDwaUYQt6t
Swissborg: NttBm3HouTCFnUBz32fEs5joQFRjFoJPA8AyhtgjFrw
Cheese: NTtxeqz2XjMnpcEoWMqb6pz84zHweJRYWyzmsmmW49E
Agora: NttADdCvGLUhukNyePei9CkmHoe6S9xjqgqfQv51PQg
xBorg: NttXP2tPLxGkNA3yrSfFZbtDbfKPKBrJUR6Jcqh6sRi
WXM: NttWixqwUHAnpXym3UYUySQZtb4C57EZxpH721JfLyF

[Blockchain Watcher] (SOLANA - FIX) Map new contracts for NTT

---

blockchain-watcher/src/domain/entities/events.ts
blockchain-watcher/src/infrastructure/mappers/solana/solanaTransferRedeemedMapper.ts

- [#1480](https://github.com/wormhole-foundation/wormhole-explorer/issues/1480)[#1480](https://github.com/wormhole-foundation/wormhole-explorer/issues/1480)
Map from and to for solana redeem events
- TX: https://wormholescan.io/#/tx/Rg1pfKvrRJrVXtAbRGi4ZVHcEwJN8wrrV8CiE9P7KbbusDHRmMU86V3AaSD1mHgTbZTHh5FdsKiv7LfjmZGA9xZ
- form: signer
- to: wormhole core

[Blockchain Watcher] (SOLANA) Map from and to for solana

---

api/handlers/transactions/repository.go

- Issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/1542

hotfix for query chain-activity

---

api/docs/docs.go
api/docs/swagger.json
api/docs/swagger.yaml
api/routes/wormscan/operations/response.go

- Add new fee fields to `/operations` response.
- Example: https://api.staging.wormscan.io/api/v1/operations?txHash=4019cee9de355fb5395d51be86a22f9f97a29bc7f800d6978563f4761eac1d5a
```
{
"operations": [
{
"id": "16/000000000000000000000000b1731c586ca89a23809861c6103f0b96b3f57d92/82043",
"sourceChain": {
"chainId": 16,
"timestamp": "2024-07-15T17:13:48Z",
"transaction": {
"txHash": "0x4019cee9de355fb5395d51be86a22f9f97a29bc7f800d6978563f4761eac1d5a"
},
"from": "0x3aab6779d50181ce73a1fe5b2f545a09eb70eec8",
"status": "confirmed",
"fee": "0.0375625",
"gasTokenNotional": "0.214743",
"feeUSD": "0.0080662839375"
},
"targetChain": {
"chainId": 5,
"timestamp": "2024-07-15T17:14:33Z",
"transaction": {
"txHash": "cf9dc2fe25ed12bfde75bab0dd3bd14aaa40b20f3cbee4a74f4cee9dbf8b708e"
},
"status": …
```

Add fees fields to /operations endpoint

---

blockchain-watcher/config/default.json
blockchain-watcher/config/mainnet.json
blockchain-watcher/src/common/wormchain.ts
blockchain-watcher/src/domain/actions/wormchain/GetWormchainLogs.ts
blockchain-watcher/src/domain/actions/wormchain/GetWormchainRedeems.ts
blockchain-watcher/src/domain/actions/wormchain/PollWormchain.ts
blockchain-watcher/src/domain/repositories.ts
blockchain-watcher/src/infrastructure/repositories/RepositoriesBuilder.ts
blockchain-watcher/src/infrastructure/repositories/wormchain/RateLimitedWormchainJsonRPCBlockRepository.ts
blockchain-watcher/src/infrastructure/repositories/wormchain/WormchainJsonRPCBlockRepository.ts
blockchain-watcher/test/domain/actions/wormchain/GetWormchainLogs.test.ts
blockchain-watcher/test/domain/actions/wormchain/GetWormchainRedeems.test.ts
blockchain-watcher/test/domain/actions/wormchain/PollWormchain.test.ts
blockchain-watcher/test/infrastructure/repositories/WormchainJsonRPCBlockRepository.test.ts

- Improve how create the providers for wormchain using a pool of them

[Blockchain Watcher] (WORMCHAIN) Improve how create the providers

---

blockchain-watcher/config/mainnet.json
blockchain-watcher/package.json
blockchain-watcher/src/infrastructure/repositories/RateLimitedRPCRepository.ts
blockchain-watcher/src/infrastructure/repositories/RepositoriesBuilder.ts
blockchain-watcher/src/infrastructure/repositories/algorand/RateLimitedAlgorandJsonRPCBlockRepository.ts
blockchain-watcher/src/infrastructure/repositories/aptos/RateLimitedAptosJsonRPCBlockRepository.ts
blockchain-watcher/src/infrastructure/repositories/common/rateLimitedOptions.ts
blockchain-watcher/src/infrastructure/repositories/cosmos/RateLimitedCosmosJsonRPCBlockRepository.ts
blockchain-watcher/src/infrastructure/repositories/evm/EvmJsonRPCBlockRepository.ts
blockchain-watcher/src/infrastructure/repositories/evm/RateLimitedEvmJsonRPCBlockRepository.ts
blockchain-watcher/src/infrastructure/repositories/solana/RateLimitedSolanaSlotRepository.ts
blockchain-watcher/src/infrastructure/repositories/sui/RateLimitedSuiJsonRPCBlockRepository.ts
blockchain-watcher/src/infrastructure/repositories/wormchain/RateLimitedWormchainJsonRPCBlockRepository.ts
blockchain-watcher/src/infrastructure/rpc/http/HealthyProvidersPool.ts
blockchain-watcher/src/infrastructure/rpc/http/InstrumentedHttpProvider.ts
blockchain-watcher/test/infrastructure/repositories/RateLimitedSolanaSlotRepository.test.ts
deploy/blockchain-watcher/workers/circle-message-sent-events-1.yaml
deploy/blockchain-watcher/workers/target-events-3.yaml

- Validate tx process in repository
- Change commitment for circle jobs to latest
- Add chain in rateLimited logs and map interval and attempts variable for config

[Blockchain Watcher] (FIX) Improve code

---

deploy/blockchain-watcher/workers/backfiller.yaml
deploy/blockchain-watcher/workers/circle-message-sent-events-1.yaml
deploy/blockchain-watcher/workers/solana-source-events-1.yaml
deploy/blockchain-watcher/workers/solana-target-events-1.yaml
deploy/blockchain-watcher/workers/source-events-1.yaml
deploy/blockchain-watcher/workers/source-events-2.yaml
deploy/blockchain-watcher/workers/source-events-3.yaml
deploy/blockchain-watcher/workers/target-events-1.yaml
deploy/blockchain-watcher/workers/target-events-2.yaml
deploy/blockchain-watcher/workers/target-events-3.yaml

- [#1626](https://github.com/wormhole-foundation/wormhole-explorer/issues/1626)
- Add RollingUpdate strategy in pods deploy
- When you re-deploy a new version with existing pods we kill it the latest and replace it with the news

[Blockchain Watcher] (CONFIG) Add RollingUpdate strategy in pods deploy

---

blockchain-watcher/src/domain/actions/aptos/GetAptosTransactions.ts
blockchain-watcher/src/domain/actions/aptos/GetAptosTransactionsByEvents.ts
blockchain-watcher/src/domain/actions/aptos/PollAptos.ts
blockchain-watcher/test/domain/actions/aptos/GetAptosTransactions.test.ts
blockchain-watcher/test/domain/actions/aptos/GetAptosTransactionsByEvents.test.ts

- [#1649](https://github.com/wormhole-foundation/wormhole-explorer/issues/1649)
- Improve aptos process validating the latest block version
- Run locally process and increase latest limit
- Get the latest source tx
- Get the latest redeem tx

[Blockchain Watcher] (APTOS) Improve aptos process validating the latest block version

---

blockchain-watcher/src/domain/actions/near/PollNear.ts

- Validate outdated process
- The rpc returns an old block position and we outdated it

[Blockchain Watcher] (NEAR - FIX) Validate outdated process

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/target-events-2.yaml

[#1644](https://github.com/wormhole-foundation/wormhole-explorer/issues/1681)
- Map contract for standard relayer

[Blockchain Watcher] (STANDARD RELAYER - SNAXCHAIN) Map contract for standard relayer

---

blockchain-watcher/src/infrastructure/repositories/RepositoriesBuilder.ts
blockchain-watcher/src/infrastructure/repositories/solana/Web3SolanaSlotRepository.ts
blockchain-watcher/src/infrastructure/rpc/http/InstrumentedConnectionWrapper.ts
blockchain-watcher/test/infrastructure/repositories/Web3SolanaSlotRepository.test.ts
deploy/blockchain-watcher/workers/solana-source-events-1.yaml
deploy/blockchain-watcher/workers/solana-target-events-1.yaml

[#1644](https://github.com/wormhole-foundation/wormhole-explorer/issues/1644)
- Create wrapper and offline method
- Validate when we cannot get the block object and we need retry
- We can figure out this codes to improve the SolanaFailure mapper: (this.code === -32007 || this.code === -32009)

[Blockchain Watcher] (SOLANA) Create wrapper and offline method

---

deploy/blockchain-watcher/workers/circle-message-sent-events-1.yaml
deploy/blockchain-watcher/workers/solana-circle-message-sent-events-1.yaml
deploy/blockchain-watcher/workers/source-events-1.yaml
deploy/blockchain-watcher/workers/target-events-3.yaml

- Split circle job in evm and solana
Yesterday we had a problem with the resources in this pod. The solution was to dedicate a particular job for evm and solana
Restarting pod

[Blockchain Watcher] (JOB) Split circle jobs in evm and solana

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/target-events-3.yaml

Map standard relayer in klaytn
- issue
- Run process

[Blockchain Watcher] (KLAYTN) Map standard relayer in klaytn

---

api/handlers/protocols/repository.go
api/handlers/protocols/service_test.go

 fix query and unit-test of allbridge

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/solana-target-events-1.yaml

https://xlabs-xyz.atlassian.net/browse/WS-39
Map NTT contact for solana:
- A7VwadM5nSiCtmEe5XZ3AjyXBKfePF2EPnY5wZbaWJjq
- BopVWeP7ctdHU4x2GrbZX7XM13RPrfC45hUmcQz621Y8
At the moment we dont have tx to test the redeem
- A7VwadM5nSiCtmEe5XZ3AjyXBKfePF2EPnY5wZbaWJjq
https://solscan.io/account/A7VwadM5nSiCtmEe5XZ3AjyXBKfePF2EPnY5wZbaWJjq
- BopVWeP7ctdHU4x2GrbZX7XM13RPrfC45hUmcQz621Y8
https://solscan.io/account/BopVWeP7ctdHU4x2GrbZX7XM13RPrfC45hUmcQz621Y8

[Blockchain Watcher] (NTT - SOLANA) Map NTT contracts for solana

---

api/handlers/governor/model.go
api/handlers/governor/mongo_repository.go
api/handlers/governor/postgres_repository.go
api/handlers/governor/service.go
api/routes/wormscan/governor/controller.go

- Migration of endpoint /governor/notional/limit to postgres

Migration of endpoint /governor/notional/limit to postgres

---

blockchain-watcher/config/custom-environment-variables.json
blockchain-watcher/config/default.json
blockchain-watcher/src/infrastructure/repositories/RepositoriesBuilder.ts
blockchain-watcher/test/infrastructure/repositories/RepositoriesBuilder.test.ts
blockchain-watcher/test/mocks/configMock.ts
deploy/blockchain-watcher/workers/source-events-3.yaml
deploy/blockchain-watcher/workers/target-events-3.yaml

https://xlabs-xyz.atlassian.net/browse/WS-9
Map berachin in testnet
- core contract: 0xBB73cB66C26740F31d1FabDC6b7A46a038A300dd
- token bridge: 0xa10f2eF61dE1f19f586ab8B6F2EbA89bACE63F7a
- test source event

[Blockchain Watcher] (BERACHAIN) Map berachain in testnet

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/solana-target-events-1.yaml

https://xlabs-xyz.atlassian.net/browse/WS-42
Map NTT contract for layer3 in solana
- Contract: NTtn3BrY2jt8cZqptVgeGpw8Pcrnr6yDfWR8aMN6bhB
- test process tx locally
- tx: https://wormholescan.io/#/tx/0x941a1a2e07258399a9a74202de5952b0ac271b418af09afadc3a4667f81dc01e

[Blockchain Watcher] (NTT - layer3) Map NTT contract for layer3 in solana

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
deploy/blockchain-watcher/workers/solana-target-events-1.yaml

https://xlabs-xyz.atlassian.net/browse/WS-42
Map NTT contract for layer3 in solana
- Contract: nTTVLsyTqRZFSyphRjkgi1Bxp5aR7nXDmMGerNWm2a6

[Blockchain Watcher] (NTT - layer3) Replace layer3 contract in solana

---

api/handlers/governor/model.go
api/handlers/governor/mongo_repository.go
api/handlers/governor/postgres_repository.go
api/handlers/governor/service.go
api/routes/wormscan/governor/controller.go

- Migrate endpoint `/api/v1/governor/notional/available/{chainId}`

migrate /governor/notional/available/:chainId to postresql

---

api/handlers/governor/model.go
api/handlers/governor/mongo_repository.go
api/handlers/governor/postgres_repository.go
api/handlers/governor/service.go
api/routes/wormscan/governor/controller.go

- migrate `/governor/notional/available`

migrate governor-notional-available

---

blockchain-watcher/src/domain/actions/sui/PollSuiTransactions.ts
blockchain-watcher/test/domain/actions/sui/PollSuiTransactions.test.ts
deploy/blockchain-watcher/workers/target-events-3.yaml

https://xlabs-xyz.atlassian.net/browse/WS-46
Improve sui process using multiple filters

[Blockchain Watcher] (SUI) Improve sui process using array of filters

---

api/handlers/governor/model.go
api/handlers/governor/mongo_repository.go
api/handlers/governor/postgres_repository.go
api/handlers/governor/service.go
api/routes/wormscan/governor/controller.go

- migrate `/api/v1/governor/notional/max_available/1`

Migrate governor notional max available

---

api/handlers/protocols/service.go
api/routes/wormscan/protocols/controller_test.go

- Ticket: JIRA WS-5
- Add `last_day_diff_volume_percentage` to `/protocols/stats` response.

add last_day_diff_volume_percentage to /protocols/stats

---

api/handlers/governor/model.go
api/handlers/governor/postgres_repository.go
api/handlers/governor/service.go
api/routes/wormscan/governor/controller.go

- Migrate `/governor/enqueued_vaas`
- Migrate `/governor/enqueued_vaas/:chain_id`

 migrate /governor/enqueued-vaas

---

blockchain-watcher/src/infrastructure/repositories/target/SnsEventRepository.ts

- We create a message attributes to be able to filters in sns subscription 
The value will be the name of events, example: "transfer-redeemed", "log-message-published", etc

[Blockchain Watcher] (NTT - SOLANA) Map MessageAttributes

---

blockchain-watcher/config/mainnet.json
blockchain-watcher/src/domain/actions/solana/PollSolanaTransactions.ts

https://xlabs-xyz.atlassian.net/browse/WS-75
Improve solana process using promise.allSettled to get transactions
- Latest process:
- New process:

[Blockchain Watcher] (SOLANA) Improve process using promise.allSettled

---

blockchain-watcher/src/infrastructure/mappers/evm/evmLogCircleMessageSentMapper.ts
blockchain-watcher/src/infrastructure/mappers/utils/circle.ts

We have trying to parse an unknown cctp domain:

[Blockchain Watcher](FIX - CIRCLE) Validate payload parser

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
common/domain/manual_mainnet_tokens.go
deploy/blockchain-watcher/workers/solana-target-events-1.yaml

USDS NTT manager: STTb3N8SdASycVjRhgPZV7EgtdaW19pkuY5vGxTNEW6
SKY NTT manager: STTrhNsZyLN3srkazdo6LnpJ5RciJYP9N4zVwwYycw9
Issue: https://xlabs-xyz.atlassian.net/browse/POR-116

Remove USDS and SKY config

---

blockchain-watcher/src/infrastructure/mappers/contractsMapperConfig.json
common/domain/manual_mainnet_tokens.go
deploy/blockchain-watcher/workers/solana-target-events-1.yaml

USDS Solana token: `USDSwr9ApdHk5bvJKMjzff41FfuX8bSxdKcR81vTwcA`
USDS Solana NTT manager: `STTUVCMPuNbk21y1J6nqEGXSQ8HKvFmFBKnCvKHTrWn`

Update USDS NTT
