- fly/go.mod
- fly/main.go
Having the module be canonical enables other modules to import it.
> Adjust module name to be canonical

- fly/storage/repository.go
99% of our storage costs is due to pyth observations. Since we're not storing all of pyth's vaas, it makes sense to avoid storing its observations as well.
Closes #48
> Do not store pythnet observations

- api/main.go
- old legacy endpoint now have `/v1/` prefix only 
- new endpoints have `/api/v1`
> remove prefix

- api/docs/controllers.go
- api/docs/docs.go
- api/docs/swagger.json
- api/docs/swagger.yaml
- api/main.go
Expose the API's swagger spec under the route `GET /swagger.json`
> [API] Add route `GET /swagger.json`

- api/main.go
- api/routes/guardian/governor/controller.go
- api/routes/guardian/guardian/controller.go
- api/routes/guardian/heartbeats/controller.go
- api/routes/guardian/routes.go
- api/routes/guardian/vaa/controller.go
- api/routes/wormscan/governor/controller.go
- api/routes/wormscan/infrastructure/controller.go
- api/routes/wormscan/observations/controller.go
- api/routes/wormscan/routes.go
- api/routes/wormscan/vaa/controller.go
Split `/v1` and `/api/v1` controllers into different packages (respectively `api/routes/guardian` and `api/routes/wormscan`).
Still need to move services/repositories/models according to the new package layout.
> [API] split api/v1 and v1 routing in different files

- .github/workflows/pr_build.yml
This will help prevent the API swagger docs from breaking
> Build API swagger on github workflows

- api/docs/docs.go
- api/docs/swagger.json
- api/docs/swagger.yaml
- api/handlers/vaa/model.go
- api/handlers/vaa/repository.go
- api/handlers/vaa/service.go
- api/routes/wormscan/vaa/controller.go
The structs `VaaDoc` and `VaaWithPayload` were being used for similar purposes.
This commit merges both into the same struct.
> [API] Remove duplicated model for VAAs

- api/handlers/governor/repository.go
- api/handlers/governor/service.go
- api/handlers/observations/repository.go
- api/handlers/vaa/repository.go
- api/handlers/vaa/service.go
- api/internal/pagination/pagination.go
- api/middleware/extract_pagination.go
- api/middleware/extract_parameters.go
- api/routes/wormscan/governor/controller.go
- api/routes/wormscan/observations/controller.go
- api/routes/wormscan/routes.go
- api/routes/wormscan/vaa/controller.go
* On all endpoints, fix the behavior of the `page` parameter (which was previously being ignored).
* On `GET /api/v1/vaas`, fix the behavior of the `sortBy` parameter (which wasn't working when `parsedPayload=true`).
* For all endpoints, validate the query parameters `page`, `pageNumber` and `sortOrder`.
* Return descriptive errors when pagination-related parameters happen to be invalid (`page`, `pageSize`, `sortOrder`)
* Validate guardian addresses in query params
All parameters involved were manually tested
> [API] Several fixes related to pagination

- api/handlers/governor/repository.go
- api/routes/wormscan/governor/controller.go
- api/routes/wormscan/routes.go
Previously, when calling `GET /api/v1/governor/enqueued_vaas`, it returned a status code of 404 when there were no enqueued VAAs.
Now, the endpoint returns a status code of 200, and the response body contains an empty array.
> [API] Change status code for enqueued VAAs endpoint

- api/handlers/vaa/repository.go
- api/handlers/vaa/service.go
- api/internal/pagination/pagination.go
In some cases, the query parameters for a MongoDB aggregation pipeline were not being initialized.
This led to errors in `GET /api/v1/vaas/{chain}/{emitter}/{seq}`. Other endpoints could also have been affected.
> [API] Fix issue in MongoDB aggregation pipeline

- api/docs/docs.go
- api/docs/swagger.json
- api/docs/swagger.yaml
- api/handlers/governor/repository.go
- api/routes/wormscan/governor/controller.go
Changes to `GET /api/v1/governor/limit`:
* Fix the behavior of the parameters `page` and `pageSize` (which previously were being ignored).
* When no results are found, return an HTTP status code of 200 and set the response to an empty array.
* Remove the `sortOrder` query parameter.
The rationale for removing the `sortOrder` parameter is that sorting chains by ascending/descending chain ID doesn't seem to be a useful operation.
> [API] Several fixes in `GET /api/v1/governor/limit`

- api/docs/docs.go
- api/docs/swagger.json
- api/docs/swagger.yaml
- api/routes/wormscan/governor/controller.go
The API's swagger documentation exposes a route `GET /api/v1/governor/max_available/:chain`, but instead it should be `GET /api/v1/governor/notional/max_available/:chain`.
> [API] Fix incorrect route in swagger docs

- api/docs/docs.go
- api/docs/swagger.json
- api/docs/swagger.yaml
- api/handlers/governor/repository.go
- api/handlers/governor/service.go
- api/internal/pagination/pagination.go
- api/routes/wormscan/governor/controller.go
* Swagger: remove `sortOrder` query parameter from several endpoints in which it didn't make sense.
* Swagger: remove query params `page` and `pageSize` from endpoints that return a single object.
* Sort the output of `GET /api/v1/governor/config` by ascending id.
* Refactor: remove duplicated code, format code for readability.
> [API] Remove unused query params from swagger docs

- api/handlers/governor/repository.go
- api/handlers/governor/service.go
- api/handlers/observations/service.go
- api/handlers/vaa/service.go
- api/middleware/extract_parameters.go
- api/routes/guardian/governor/controller.go
- api/routes/guardian/vaa/controller.go
- api/routes/wormscan/governor/controller.go
- api/routes/wormscan/vaa/controller.go
- api/rpc/handler.go
- api/types/address.go
- api/types/address_test.go
Context: https://github.com/wormhole-foundation/wormhole-explorer/issues/154
This PR modifies all endpoints that receive an emitter/guardian address to accept a wider range of formats.
After this pull request, all of these are equivalent:
* `0x000000000000000000000000f890982f9310df57d00f659cf4fd87e65aded8d7`
* `000000000000000000000000f890982f9310df57d00f659cf4fd87e65aded8d7`
* `0xf890982f9310df57d00f659cf4fd87e65aded8d7`
* `f890982f9310df57d00f659cf4fd87e65aded8d7`
* Added unit tests for the parsing code.
* Tested manually a few of the affected endpoints.
> [API] Accept additional address formats

- fly/main.go
Fix an issue in which fly was not correctly populating the `P2P_NETWORK` variable from an `.env` file.
> [FLY] Fix an issue related to `.env` files

- go.work
Use a Go workspace to simplify working with multiple modules at a time.
> Use a Go workspace

- api/handlers/governor/repository.go
- api/handlers/governor/service.go
- api/routes/wormscan/governor/controller.go
- api/types/address.go
A few governor endpoints were handling addresses incorrectly, which resulted in errors:
* `GET /api/v1/governor/config/{governor_address}`
* `GET /api/v1/governor/status/{governor_address}`
Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/201
This commit fixes the issue and adds doc comments to prevent the same caveat from happening again in the future.
> [API] Fix governor endpoints

- api/handlers/observations/repository.go
- api/handlers/vaa/repository.go
- api/routes/guardian/heartbeats/controller.go
Several endpoints related to VAAs and observations returned `null` when no results were found.
This commit changes the behavior to return `[]` instead, which is more ergonomic for users.
Endpoints affected:
- `GET /api/v1/observations/:chain`
- `GET /api/v1/observations/:chain/:emitter`
- `GET /api/v1/observations/:chain/:emitter/:sequence`
- `GET /api/v1/observations/:chain/:emitter/:sequence/:signer/:hash`
- `GET /api/v1/vaas/{chain_id}`
- `GET /api/v1/vaas/{chain_id}/{emitter}`
- `GET /api/v1/vaas/{chain_id}/{emitter}/{seq}`
> [API] Fix serialization issue in HTTP responses

- api/docs/docs.go
- api/docs/swagger.json
- api/docs/swagger.yaml
- api/handlers/transactions/model.go
- api/handlers/transactions/repository.go
- api/handlers/transactions/service.go
- api/routes/wormscan/routes.go
- api/routes/wormscan/transactions/controller.go
- api/routes/wormscan/transactions/response.go
This pull request adds the `GET /api/v1/scorecards` endpoint, which is required by the wormscan frontend.
Most of the fields that this endpoint should return are being omitted because the data is not currently available on the backend. Those fields will be added iteratively as the data becomes available.
The current format of the response is:
```json
{
"total_tx_count": "1300200",
"24h_tx_count": "4200"
}
```
Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/221
In order to populate the `"total_tx_count"` metric, a task is needed in influxdb:
```
$ cat total-vaa-count.flux 
option task = {
name: "Total number of emitted VAAs",
every: 1m
}
from(bucket: "wormhole-explorer")
|> range(start: 2018-01-01T00:00:00Z)
|> filter(fn: (r) => r._measurement == …
```
> [API/ANALYTICS] Scorecards endpoint

- api/handlers/governor/repository.go
- api/handlers/observations/repository.go
- api/handlers/vaa/repository.go
- api/internal/pagination/pagination.go
- api/middleware/extract_pagination.go
The output of `GET /api/v1/vaas` was not being correctly sorted. This pull request changes the behavior so that the output will be sorted by the `timestamp` field.
Additionally, duplicated code was removed in the VAA code that handles queries.
Also, there was an unused query parameter `sortBy` which was being exposed but not used. Hence it was removed.
Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/233
> Sort the output of `GET /api/v1/vaas` by timestamp

- api/handlers/transactions/repository.go
- api/routes/wormscan/transactions/controller.go
- api/routes/wormscan/transactions/response.go
The endpoint `GET /api/v1/scorecards` was returning an inaccurate number for the volume metric. This pull request fixes the issue.
Additionally, the response model of `GET /api/v1/top-assets-by-volume` has been changed as specified by @raop155:
```
{
"assets": [
{
"symbol": "USDCet",
"tokenChain": 1,
"tokenAddress": "000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
"volume": "475173.83806883"
}
]
}
```
> Fix inaccurate volume in `GET /api/v1/scorecards`

- api/docs/docs.go
- api/docs/swagger.json
- api/docs/swagger.yaml
- api/handlers/observations/repository.go
- api/routes/wormscan/observations/controller.go
This pull request fixes an issue in which all observation-related endpoints were returning results sorted by `id` (https://github.com/wormhole-foundation/wormhole-explorer/issues/358). The expected behavior is to sort results based on descending timestamp order instead.
Also, swagger docs were updated to document this behavior.
> [API] Fix sorting order in observation endpoints

- common/client/cache/notional/cache.go
When initializing the notional cache, if there was more than one page of results, the client would run into an infinite loop.
This issue was causing several services to stall on startup in the staging environment (API, analytics, etc).
(For an example of how we're supposed to iterate over redis `Scan()` results, check this [documentation](https://pkg.go.dev/github.com/go-Redis/redis#Client.Scan))
> Fix an infinite loop in redis cache client

- analytics/cmd/service/run.go
- analytics/config/config.go
- analytics/metric/metric.go
- analytics/metric/mongo.go
- deploy/analytics/analytics-service.yaml
Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/377
This pull request modifies the analytics service so that it persists price information for a VAA in MongoDB. Data is stored only for token bridge VAAs, and only if the price is cached for the symbol being used.
A new collection `transferPrices` has been created, with the following document model:
```
{
"_id": "22/0000000000000000000000000000000000000000000000000000000000000001/18087",
"price": "0.999684",
"symbol": "USDC",
"timestamp": 2023-06-06T14:04:47.000+00:00
"tokenAmount": "0.1",
"usdAmount": "0.0999684"
}
```
> Persist symbol and price for VAAs

- api/routes/wormscan/transactions/controller.go
- deploy/tx-tracker-backfiller/tx-tracker-backfiller-job.yaml
- deploy/tx-tracker/tx-tracker-service.yaml
- tx-tracker/chains/aptos.go
- tx-tracker/chains/tx.go
- tx-tracker/cmd/fetchone/main.go
- tx-tracker/config/structs.go
This pull request adds support for Aptos in the `tx-tracker` service.
This will lead to improvements for the wormhole Scan UI:
1. The transaction hash that was being previously displayed for Aptos VAAs was incorrect. This pull request fixes the issue.
2. The sender addresses for Aptos VAAs will now become available for for the UI.
> Add support for Aptos in the `tx-tracker` service

- api/types/tx_hash.go
- api/types/tx_hash_test.go
Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/434
Some Solana transaction hashes were failing to parse. This pull request fixes the issue.
> Fix tx hash parsing for Solana

- api/handlers/vaa/model.go
Remove the `NativeTxHash` from the JSON model returned by `GET /api/v1/vaas`. That field was never meant to be exposed to the API users.
> Remove field `vaa.NativeTxHash` from JSON model

- api/handlers/vaa/repository.go
Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/493
Fix an issue in which transaction hash search was failing for VAAs that have the same `txHash`.
> Fix issue in `txHash` search

- api/docs/docs.go
- api/docs/swagger.json
- api/docs/swagger.yaml
- api/internal/config/config.go
- api/main.go
- deploy/api/api-service.yaml
The `api` component was importing and initializing the notional cache, but not using it.
This pull request removes the unnecessary dependency.
> Remove notional cache from the `api` component

- tx-tracker/cmd/service/main.go
- tx-tracker/consumer/consumer.go
- tx-tracker/consumer/processor.go
- tx-tracker/consumer/repository.go
- tx-tracker/consumer/workerpool.go
- tx-tracker/queue/vaa_sqs.go
This pull request implements improvements in the `tx-tracker` service:
* Adjust SQS visibilityTimeout.
* Process PythNet messages concurrently (this will make it easier for the service to catch up if there are a lot of messages in the input queue).
* Add more context information to error messages.
> Improvements in the `tx-tracker` service

- api/docs/docs.go
- api/docs/swagger.json
- api/docs/swagger.yaml
- api/handlers/transactions/model.go
- api/handlers/transactions/repository.go
This pull request removes two unused fields from the `GlobalTransaction.OriginTx` JSON model:
* `timestamp`: this field is always set to the VAA's timestamp, making it redundant. Moreover, for EVM chains we need one extra RPC node request to get it. So better get rid of it.
* `chainId`: this field is always set to the VAA's emitter chain, making it redundant.
> Remove unused fields from the origin transaction model

- common/domain/chainid.go
- deploy/tx-tracker-backfiller/env/production.env
- deploy/tx-tracker-backfiller/env/staging.env
- deploy/tx-tracker-backfiller/env/test.env
- deploy/tx-tracker/env/production.env
- deploy/tx-tracker/env/staging.env
- deploy/tx-tracker/env/test.env
- tx-tracker/chains/chains.go
- tx-tracker/config/structs.go
Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/569
This pull request adds support for the "Base" blockchain in different parts of the codebase:
* The functions `domain.TranslateEmitterAddress`, `domain.EncodeTrxHashByChainID` and `domain.DecodeNativeAddressToHex`.
* The `tx-tracker` service: it now connects to a Base RPC node to fetch origin transaction metadata.
> `tx-tracker`: add support for the "Base" blockchain

- api/handlers/vaa/repository.go
- api/handlers/vaa/service.go
- api/routes/wormscan/vaa/controller.go
Before this pull request, when calling `GET /api/v1/vaas?txHash={h}` for a hash that has multiple VAAs associated with it, we were just returning one. After this pull request, the API should return all of the VAAs associated with that transaction hash.
Tracking issue: https://github.com/wormhole-foundation/wormhole-explorer/issues/563
> Handle multiple VAAs with the same `txHash`

- api/handlers/transactions/repository.go
- common/domain/chainid.go
Tracking issues: https://github.com/wormhole-foundation/wormhole-explorer/issues/572, https://github.com/wormhole-foundation/wormhole-explorer/issues/573
This pull request fixes an issue in which the endpoint `GET /api/v1/top-chain-pairs-by-num-transfers` was returning invalid chain IDs for testnet.
> Exclude invalid chain IDs from top chain pairs

- api/docs/docs.go
- api/docs/swagger.json
- api/docs/swagger.yaml
- api/handlers/vaa/repository.go
- api/handlers/vaa/service.go
- api/middleware/extract_parameters.go
- api/routes/wormscan/vaa/controller.go
This pull request adds the parameter `toChain` to the endpoint `GET /api/v1/vaas/{emitterChain}/{emitterAddress}`.
Other VAA-related endpoints do not support this parameter.
Additionally, for performance reasons, a composite index must be created in MongoDB: `db.parsedVaa.createIndex({"emitterChain": -1, "emitterAddr": -1, "rawStandardizedProperties.toChain": -1, "indexedAt": -1})`
> [API] Add `toChain` filter to `GET /api/v1/vaas/{emitterChain}/{emitterAddr}`

- .gitignore
Update `.gitignore` file to ignore these files from `event-watcher` folder:
> node_modules/
> lib/
> dist/
> *.log
> db.json
> lastBlockByChain.json
> .env
> serviceAccountKey.json
> bigtableAccountKey.json
> tsconfig.tsbuildinfo
> serviceAccount.json
> fix(.gitignore): ignore files from event-watcher

- tx-tracker/README.md
This pull request adds a README.md file explaining how the `tx-tracker` service works.
> Add documentation for the `tx-tracker` service

- api/handlers/relays/repository.go
- changes the search criteria for `_id` for relayer data
- this will make all the current data invalid. We need to backfil.
> change search key for _id

- event-watcher/src/consts.ts
- event-watcher/src/databases/MongoDB.ts
- event-watcher/src/databases/types.ts
- event-watcher/src/databases/utils.ts
- event-watcher/src/index.ts
- event-watcher/src/watchers/EVMWatcher.ts
- Enhance behavior when finding the `TransferRedeemed` event
1. If the document does not exist -> insert the document with data available from logs
2. If the document does exist
2.1. if `destinationTx` field does not exist -> insert the `destinationTx` field into the document with data available from logs
2.2 if `destinationTx` field exists -> **none**
> fix: persist behavior when finding redeemed events

- blockchain-watcher/config/default.json
- blockchain-watcher/config/mainnet.json
Remove ankr public node usage in BW. Ankr looks at IPs to apply limits and could apply hard rate limiting on private nodes if we go over the threshold on public nodes.
> bw: remove ankr public nodes usage

- blockchain-watcher/src/domain/actions/evm/HandleEvmTransactions.ts
- blockchain-watcher/src/infrastructure/mappers/evm/evmRedeemedTransactionFoundMapper.ts
- blockchain-watcher/src/infrastructure/mappers/solana/solanaTransferRedeemedMapper.ts
- blockchain-watcher/test/infrastructure/mappers/evm/evmRedeemedTransactionFoundMapper.test.ts
- 
- Fix when try to match contract address with address inside events
-
> [Blockchain Watcher] (FIX) Add lowecasse in contracts addresses

- .gitignore
- analytics/scripts/protocols_stats_1d.flux
- analytics/scripts/protocols_stats_1h.flux
- api/handlers/protocols/repository.go
- api/handlers/protocols/service.go
- api/handlers/protocols/service_test.go
- api/internal/metrics/prometheus.go
- api/main.go
- api/routes/wormscan/protocols/controller_test.go
- common/dbconsts/consts.go
[ISSUE-1089] Collect CCTP - Metrics - WIP
- Issues: https://github.com/wormhole-foundation/wormhole-explorer/issues/1089
- Influx_task: 
- 1) *every hour*: collect cctp and portal_token_bridge metrics from `vaa_volume_v2` measurement. Sum `total_value_transferred` and `total_messages` and store it in *bucket 30 days*.
- 2) *every day*: sum the last day metrics from _internal_protocols_stats_1h_ and store it in _internal_protocols_stats_1d_ in **bucket infinite.** That'll indicate what happened during that last day.
- Add logic in `/protocols/stats` handler service to return stats of CCTP and PORTAL TOKEN BRIDGE:
```
[
{
"protocol": "allbridge",
"total_messages": 34202,
"total_value_transferred": 15459629.317363381,
"last_day_messages": 39,
"last_day_diff_percentage": "0.11%"
},
{ …
```
> [ISSUE-1089] Collect CCTP - Metrics

- blockchain-watcher/src/domain/actions/sui/PollSuiTransactions.ts
- Fix currentCheckpoint value for report metrics on grafana
**_Error_**
We dont have mapping the current position for the cursor on PollSuiTransactions
> [Blockchain Watcher] (FIX - SUI) Fix currentCheckpoint value for report metrics on grafana

- api/docs/docs.go
- api/docs/swagger.json
- api/docs/swagger.yaml
- api/handlers/operations/repository.go
- api/handlers/operations/repository_test.go
- api/handlers/operations/service.go
- api/handlers/transactions/model.go
- api/handlers/transactions/repository.go
- api/handlers/transactions/repository_test.go
- api/middleware/extract_parameters.go
- api/routes/wormscan/operations/controller.go
- api/routes/wormscan/transactions/controller.go
- #1335 
- Support querying with multiple sourceChains and targetChains in `/operations` endpoint.
- Support querying with multiple sourceChains,targetChains and appIds in `/transactions` endpoint.
- Add unit-tests to query builder methods.
- Search operations by multiple source chain,target chain and appIds
[/api/v1/operations?sourceChain=6,10004&targetChain=1,2,4&appId=CCTP_WORMHOLE_INTEGRATION,PORTAL_TOKEN_BRIDGE&exclusiveAppId=false](https://api.testnet.wormscan.io/api/v1/operations?sourceChain=6,10004&targetChain=1,2,4&appId=CCTP_WORMHOLE_INTEGRATION,PORTAL_TOKEN_BRIDGE&exclusiveAppId=false)
- Search chain-activity-tops by multiple source chain,target chain and *single* appId.
[/v1/x-chain-activity/tops?from=2024-02-01T00:00:00Z&to=2024-02-15T00:00:00Z&timespan=1d&sourceChain=1,2,3,4, …
> [WORMSCAN-API-1335] Support querying with multiple sourceChains and targetChains

- blockchain-watcher/src/domain/actions/solana/GetSolanaTransactions.ts
- blockchain-watcher/src/domain/actions/solana/PollSolanaTransactions.ts
- deploy/blockchain-watcher/workers/solana-source-events-1.yaml
- deploy/blockchain-watcher/workers/solana-target-events-1.yaml
Improve execution job time. We have execution by 1.5 second the job and with this process we were a lot of issues about slot batches process (fromBlock > toBlock). 
- old time: 1.5 s
- new time: 15s
Error:
blockchain-watcher-solana-source-events-1-55cffcc977-dkrcp: error [PollSolanaTransactions][poll-log-message-published-solana] [run] Error processing items Invalid slot range: fromSlot=269882473 toSlot=269882438. Might be cause we are up to date.
Source events process:
Target events process:
> [Blockchain Watcher] (SOLANA) Change logs and execution job time

- common/domain/manual_mainnet_tokens.go
Currently not tracked. Example: https://wormholescan.io/#/tx/0xc7696e9221fd61d1740ef9be54b5b26d91a2aaef731e190ed4722d2f1209a8d4
> Add USDC.e fantom token to manual tokens config

- api/handlers/protocols/repository.go
- api/handlers/protocols/service.go
- api/handlers/protocols/service_test.go
- api/main.go
- common/dbconsts/consts.go
- Add `NTT` to `/api/v1/protocols/stats` [endpoint](https://api.staging.wormscan.io/api/v1/protocols/stats) response.
Now the endpoint responds
```
[
{
"protocol": "portal_token_bridge",
"total_messages": 3772285,
"total_value_locked": 1534312151.7121854,
"total_value_transferred": 42771606350.56895,
"last_day_messages": 2366,
"last_day_diff_percentage": "0.06%"
},
{
"protocol": "cctp",
"total_messages": 92014,
"total_value_transferred": 418753766.55635583,
"last_day_messages": 85,
"last_day_diff_percentage": "0.09%"
},
{
"protocol": "native_token_transfer",
"total_messages": 83841,
"total_value_transferred": 89346433.64697778,
"last_day_messages": 560,
"last_day_diff_percentage": "0.67%"
},
{
"protocol": "allbridge",
"total_messages": 60654,
"total_value_transferred": 66805538.050969616, …
```
> [#1495] Add NTT Protocol Data to /api/v1/protocols/stats Endpoint

- deploy/blockchain-watcher/workers/target-events-1.yaml
- deploy/blockchain-watcher/workers/target-events-2.yaml
- deploy/blockchain-watcher/workers/target-events-3.yaml
- Add new filter for celo
- Contract: 0x05ca6037eC51F8b712eD2E6Fa72219FEaE74E153
- Topic: 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
- Change interval time execution in testnet pod
- We do not have a lot traffic in testnet for this reason we can reduce the execution time
- Change interval and commitment value in acala and karura. (latest => finalized)
- We change the commitment because acala anad karura need use finalized to catch the redeems and we have reduce the execution time for this both jobs
> [Blockchain Watcher] (PODS) Change interval values

- api/handlers/transactions/repository.go
- api/handlers/transactions/repository_test.go
- Some old data points of volume and count are stored as int, instead of uint. Adding `toUInt()` guarantees that when doing `sum()` all the values have the same type.
> [1424] /x-chain-activity/tops : cast volume and count fields to uint before doing sum

- api/handlers/operations/repository.go
- api/handlers/operations/repository_test.go
- api/handlers/operations/service.go
- api/routes/wormscan/operations/controller.go
- fly/migration/migration.go
- Issue: #1528 
- Add `payloadType` filter to `/operations`.
- Create index in mongodb parsedVaa collection:
- ` db.parsedVaa.createIndex({
"parsedPayload.payloadType": 1,
"timestamp":-1,
"_id":-1
})
`
- Example: `https://api.testnet.wormscan.io/api/v1/operations?payloadType=2`
> [1528] add new filter payloadtype in operations endpoint

- api/handlers/operations/repository.go
- api/handlers/operations/repository_test.go
- api/handlers/operations/service.go
- api/routes/wormscan/operations/controller.go
- api/routes/wormscan/operations/controller_test.go
- Issue: #1589 
- Add support for multiple payloadTypes in `/operations` endpoint.
> #1589 add support for multiple payloadTypes in /operations endpoint

- api/handlers/transactions/repository.go
- Ticket: #1594 
- Add missing `group-by` clause and drop `app_id` in query for `all-time` and `1y`.
> #1594 fix x-chain-activity query

- blockchain-watcher/src/infrastructure/constants.ts
We cant parse the vaa because we dont have map the emitter contract.
- Map scroll snaxchain and blast in standard relayer emitter
- Scroll
- Snaxchain
> [Blockchain Watcher] (STANDARD RELAYER) Map scroll snaxchain and blast

- blockchain-watcher/src/infrastructure/mappers/algorand/algorandRedeemedTransactionFoundMapper.ts
- blockchain-watcher/src/infrastructure/repositories/target/SnsEventRepository.ts
Issue in production yesterday about algorand process.
- If we cant process the vaa payload we skip
- Add logic to create the trackId in sns properties (de duplicated value)
- Re-process _**vaa**_ yesterday
> [Blockchain Watcher](FIX) Fix algorand mapper

- blockchain-watcher/src/infrastructure/repositories/solana/Web3SolanaSlotRepository.ts
[#1724](https://github.com/wormhole-foundation/wormhole-explorer/issues/1724)
Remove public rpc, use it only private
Improve error manager
- Original error
- Rotate RPCs when receive it an 429 error and retry
> [Blockchain Watcher] (SOLANA - FIX) Validate request if we get and error and set up offline the rpc

- blockchain-watcher/src/infrastructure/repositories/solana/Web3SolanaSlotRepository.ts
- Only needs to reprocess in the get transactions method
Test new version:
> [Blockchain Watcher] (SOLANA) Retry only when we need to get the transactions
